apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "developenv.namespace" . }}
  name: {{ include "developserver.fullname" . }}
  labels:
    {{- include "developserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "developserver.selectorLabels" . | nindent 4 }}
